<<<<<<< HEAD
# Generated by Django 3.1.1 on 2020-12-23 22:55
=======
# Generated by Django 3.1.1 on 2020-11-04 16:58
>>>>>>> b828d8e30ae34c335fc9150203a66c373a50b557

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('full_name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
=======
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
>>>>>>> b828d8e30ae34c335fc9150203a66c373a50b557
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
