# Generated by Django 3.1.1 on 2020-11-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yearn_finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='l_name',
        ),
    ]
